enum MODULES {
    BILLING = "BILLING",
    CONTACTS = "CONTACTS",
    HR = "HR",
    NOTIFICATIONS = "NOTIFICATIONS",
    SERVICES = "SERVICES",
    SUBSCRIPTIONS = "SUBSCRIPTIONS",
    SYSTEMS = "SYSTEMS"
}
