enum QueueNames {
    OUTBOUND_SMS = "OUTBOUND_SMS",
    INBOUND_SMS = "INBOUND_SMS",
    OUTBOUND_EMAIL = "OUTBOUND_EMAIL",
    INBOUND_EMAIL = "INBOUND_EMAIL"
}
enum JobNames {
    EMAIL_SEND = "EMAIL_SEND",
    EMAIL_RECEIVE = "EMAIL_RECEIVE",
    SMS_SEND = "SMS_SEND",
    SMS_RECEIVE = "SMS_RECEIVE",
    WHATSAPP_SEND = "WHATSAPP_SEND",
    WHATSAPP_RECEIVE = "WHATSAPP_RECEIVE"
}

export { QueueNames, JobNames }