enum SETTINGS {
    BILLING = "BILLING",
    CONTACTS = "CONTACTS",
    HR = "HR",
    NOTIFICATIONS_SMTP_HOST = "NOTIFICATIONS_SMTP_HOST",
    NOTIFICATIONS_SMTP_PASS = "NOTIFICATIONS_SMTP_PASS",
    NOTIFICATIONS_SMTP_PORT = "NOTIFICATIONS_SMTP_PORT",
    NOTIFICATIONS_SMTP_USER = "NOTIFICATIONS_SMTP_USER",
    SERVICES = "SERVICES",
    SUBSCRIPTIONS = "SUBSCRIPTIONS",
    SYSTEMS = "SYSTEMS"
}
